feat: preparing repo to do unit tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,7 +3,21 @@ echo 'Check for linting errors before commit'
 npm run lint || 
 (echo 'Fix eslint errors before commit' && exit 1)
 
+echo 'No lint errors :)'
+
+echo 'Lets test your code'
+
+npm run test || 
+(echo 'Check your tests! Update before commit' && exit 1)
+
+echo 'Very good! All tests passed :)'
+
+echo 'Starting the project build'
+
 npm run build || 
 (echo 'Check your code, something is happening! Update before commit' && exit 1)
+
+echo 'Project Build successfully :)!'
+
 
 echo 'Done! Its OK to commit.'
